server:
  port: 8000
spring:
    application:
        name: flashcard-service
        
#eureka is currently on an ec2, comment out serviceUrl for localhost eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://18.217.95.192:8761/eureka/
