server:
  port: 8090
spring:
    application:
        name: flashcard-studyset
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instanceId: ${spring.application.name}
    hostname: ${spring.application.name}:${server.port}
      # defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://18.217.183.112:8761/eureka/
      # defaultZone: http://18.217.95.192:8761/eureka/
  # instance:
        # instance-id: ${spring.application.name}