server:
  port: 8001
spring:
    application:
        name: flashcard-service-2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://18.217.183.112:8761/eureka/